startState='q0'
tokens = [
    'IF\n',
    'ELSE\n',
    'INT\n',
    'RETURN\n',
    'VOID\n',
    'WHILE\n',
    'PLUS\n',
    'MINUS\n',
    'TIMES\n',
    'DIVIDE\n',
    'LESS\n',
    'LESS_EQUAL\n',
    'GREATER\n',
    'GREATER_EQUAL\n',
    'EQUALS\n',
    'DIFERENT\n',
    'LPAREN\n',
    'LBRACKETS\n',
    'RBRACKETS\n',
    'LBRACES\n',
    'RBRACES\n',
    'ATTRIBUTION\n',
    'SEMICOLON\n',
    'COMMA\n',
    'RPAREN\n',
    'ID\n',
]  

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '+', '-', '*', '/', '<', '>', '=', '!', '(', ')', '[', ']', '.','{', '}', ';', ',','0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '\n']

states = [
    'q0',
    'intI', 
    'id',
    'idParenteses',
    'intN', 
    'intT',
    'iF',
    'idEspaco',
    'whileW',
    'whileH',
    'whileI',
    'whileL',
    'whileE', 
    'elseE',
    'elseL',
    'elseS',
    'elseEE', 
    'voidV',
    'voidO',
    'voidI',
    'voidD',
    'returnR',
    'returnE',
    'returnT',
    'returnU',
    'returnRR',
    'returnN',
    'mais',
    'menos',
    'maior',
    'menor',
    'maiorIgual',
    'menorIgual',
    'divide',
    'multiplicaca', 
    'igual',
    'igualId',
    'igualEspaco',
    'igualIgual',
    'diferenteEsclamacao', 
    'diferenteIgual', 
    'parentesesA', 
    'parentesesF', 
    'colcheteA',
    'colcheteF', 
    'chaveA', 
    'chaveF',
    'pontoVirgula',
    'virgula',
    'number',
    'idPontoVirgula',
    'idAParenteses',
    'idFParenteses',
    'numberEspaco',
    'numberPontoVirgula',
    'numberFParenteses',
    'numberFColchete',
    'menorNumber',
    'menorEspaco',
    'menorId',
    'numberVirgula',
    'idVirgula',
    'maiorEspaco',
    'maiorid',
    'maiorNumber',
    'idIgual',
    'idAColchete',
    'idFColchete',
    'idMultiplica',
    'idDivide',
    'idMais',
    'idMenos',
    'idAChave',
    'idFChave',
    'floatF',
    'floatL',
    'floatO',
    'floatA',
    'floatT',
    'numberPonto',
    'idDiferente',
    'idDiferenteIgual',
    'idMaior',
    'idMenor',
    
]
  

transitions = {
    'q0': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parenteses','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idEspaco': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idAColchete': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idFColchete': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

    'intI': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'iF',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'intN', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  
    'iF': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'idIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
    
    'intN': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'intT', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
    'intT': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'parentesesF','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},


  
    'id': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'id', '1': 'id', '2': 'id', '3': 'id',
              '4': 'id','5': 'id', '6': 'id', '7': 'id', '8': 'id', '9': 'id',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'idMaior','<':'idMenor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'idMais': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idMenos': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idDivide': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idMultiplica': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idVirgula': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  

  'idPontoVirgula': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idIgual': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idDiferente': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'idDiferenteIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao'},

  'idDiferenteIgual': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'idAParenteses': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idParenteses',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
'idFParenteses': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idAParenteses',')':'idFParenteses','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idAChave': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idAParenteses',')':'idFParenteses','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idFChave': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'idAParenteses',')':'idFParenteses','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
   'whileW': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'whileH', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'whileH': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'whileI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'whileI':  {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'whileL',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  
  'whileL':  {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'whileE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  
  'whileE': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'parentesesF','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},
  
  
  'elseE': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'elseL',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'elseL': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'elseS': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseEE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'elseEE': {'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'parentesesF','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},


  
  'voidV':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'voidO', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'voidO':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'voidI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'voidI':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'voidD', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'voidD':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'parentesesF','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},
  


  'returnR':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'returnE', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'returnAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

    'returnE':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'returnT', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
    'returnT':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'returnU', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

    'returnU':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnRR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'returnRR':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'returnN', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'returnN':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'parentesesF','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},


'floatF':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'floatL',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'floatL':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'floatO', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},

  'floatO':{'a': 'floatA', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
   'floatA':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'floatT', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'idIgual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'idAParenteses',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'idEspaco',' ':'idEspaco'},
  
  'floatT':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
               '+':'idMais','-':'idMenos','=':'igual','>':'maior','<':'menor','*':'idMultiplica','/':'idDivide','!':'idDiferente',
            '(':'parentesesA',')':'idFParenteses','{':'idAChave', '}':'idFChave', '[':'idAColchete',']':'idFColchete', ';':'idPontoVirgula', ',':'idVirgula','\n':'q0',' ':'q0'},


  
  'number':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao','.':'numberPonto',
            '(':'parentesesA',')':'numberFParenteses','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'numberFColchete', ';':'numberPontoVirgula',
           ',':'numberVirgula','\n':'numberEspaco',' ':'numberEspaco'},

  'numberPonto':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'numberEspaco':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'numberVirgula':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'numberFParenteses':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'numberFColchete':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'numberPontoVirgula':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'maior':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'maiorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'maiorEspaco':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'maiorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'maiorId':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'maiorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'maiorNumber':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'maiorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'menor':{'a': 'menorId', 'b': 'menorId', 'c': 'menorId', 'd': 'menorId', 'e': 'menorId', 'f': 'menorId',
              'g': 'menorId', 'h': 'menorId', 'i': 'menorId', 'j': 'menorId', 'k': 'menorId', 'l': 'menorId',
              'm': 'menorId', 'n': 'menorId', 'o': 'menorId', 'p': 'menorId', 'q': 'menorId', 'r': 'menorId',
              's': 'menorId', 't': 'menorId', 'u': 'menorId', 'v': 'menorId', 'w': 'menorId', 'x': 'menorId',
              'y': 'menorId', 'z': 'menorId', '0': 'menorNumber', '1': 'menorNumber', '2': 'menorNumber', '3': 'menorNumber',
              '4': 'menorNumber','5': 'menorNumber', '6': 'menorNumber', '7': 'menorNumber', '8': 'menorNumber', '9': 'menorNumber',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'menorEspaco',' ':'menorEspaco'},

'menorEspaco':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'menorId':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'idMenor':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'idMaior':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'menorNumber':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'menorIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'mais':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'menos':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula',' ':'q0','\n':'q0'},
  
  'maiorIgual':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'menorIgual':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'divide':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'multiplica':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  'igual':{'a': 'igualId', 'b': 'igualId', 'c': 'igualId', 'd': 'igualId', 'e': 'igualId', 'f': 'igualId',
              'g': 'igualId', 'h': 'igualId', 'i': 'igualId', 'j': 'igualId', 'k': 'igualId', 'l': 'igualId',
              'm': 'igualId', 'n': 'igualId', 'o': 'igualId', 'p': 'igualId', 'q': 'igualId', 'r': 'igualId',
              's': 'igualId', 't': 'igualId', 'u': 'igualId', 'v': 'igualId', 'w': 'igualId', 'x': 'igualId',
              'y': 'igualId', 'z': 'igualId', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igualIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'igualEspaco',' ':'igualEspaco'},

  'igualEspaco':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igualIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},  
'igualId':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igualIgual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},   

  'igualIgual':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'diferenteEsclamacao':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'diferenteIgual','>':'maior','<':'menor','*':'multiplica','/':'divide',
                '!':'diferenteEsclamacao','(':'parentesesA',')':'parentesesF','{':'chaveA', '}':
                'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',',':'virgula','\n':'q0',' ':'q0'},

  'diferenteIgual':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'parentesesA':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'parentesesF':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'colcheteA':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'colcheteF':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'chaveA':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'returnR',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'chaveF':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},

  'pontoVirgula':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula','\n':'q0',' ':'q0'},
  
  'virgula':{'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id',
              'g': 'id', 'h': 'id', 'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id',
              'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id', 'q': 'id', 'r': 'id',
              's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
              'y': 'id', 'z': 'id', '0': 'number', '1': 'number', '2': 'number', '3': 'number',
              '4': 'number','5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',
                '+':'mais','-':'menos','=':'igual','>':'maior','<':'menor','*':'multiplica','/':'divide','!':'diferenteEsclamacao',
            '(':'parentesesA',')':'parentesesF','{':'chaveA', '}':'chaveF', '[':'colcheteA',']':'colcheteF', ';':'pontoVirgula',
           ',':'virgula',' ':'q0',' \n':'q0'},

}
